version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  my-go-app:
    build: .
    container_name: my-go-app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

volumes:
  mongodb_data:
