version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  driver-location-api:
    build: .
    container_name: driver-location-api
    command: /app/cmd/driver-location-api/main
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
    environment:
      - API_KEY=${API_KEY}

  matching-api:
    build: .
    container_name: matching-api
    command: /app/cmd/matching-api/main
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    volumes:
      - .env:/app/.env
    environment:
      - API_KEY=${API_KEY}

volumes:
  mongodb_data:
